# Generated by Django 3.1.7 on 2021-03-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='desired_role',
            field=models.CharField(choices=[('ASO', 'Membre fondateur'), ('PMT', 'Résident (bureau permanent)'), ('NMD', 'Nomade (à la journée ou demi-journée)'), ('WAT', 'Sympatisant')], help_text="Veuillez préciser votre niveau d'implication dans le projet", max_length=3, verbose_name='Role désiré'),
        ),
        migrations.AlterField(
            model_name='application',
            name='max_monthly_bill',
            field=models.IntegerField(choices=[(1, 'moins de 100 euros'), (2, 'entre 100 et 200 euros'), (3, 'entre 200 et 300 euros'), (4, 'plus de 300 euros')], help_text='Veuillez indiquer quel montant maximal votre entreprise peut dépenser pour votre hébergement', verbose_name='Budget mensuel maximal'),
        ),
    ]
